### ISSUE TITLE
Create job doesn't work as expected

### ISSUE THREAD

**Issue by BinarSkugga** [googleapis/python-scheduler#37]
#### Environment details

  - OS type and version: Windows 10
  - Python version: 3.6.8
  - pip version: 20.1
  - `google-cloud-scheduler` version: 2.0.0
  - `google-api-core` version: 1.22.2

#### Steps to reproduce

  1. Create a job

#### Code example

```python
self.client = scheduler_v1.CloudSchedulerClient()
job = self.client.job_path(config.PROJECT, config.LOCATION, config.RECTIFICATION_JOB_NAME)
response = self.client.create_job(job=Job({
    'name': job,
    'http_target': HttpTarget({
        'http_method': HttpMethod['GET'],
        'headers': {'content-type': 'application/json'},
        'uri': config.API_URL + "/system/info",
    }),
    'schedule': '* * * * *',
    'time_zone': 'utc'
}))
```

#### Stack trace
```
Traceback (most recent call last):
  File "C:/Users/louis/sollumcloudplatform/src/main.py", line 29, in <module>
    application = create_app()
  File "C:\Users\louis\sollumcloudplatform\src\procedures.py", line 154, in create_app
    CloudSchedulerService.i().create_job(job={}, delay=15)
  File "C:\Users\louis\sollumcloudplatform\src\services\cloud_scheduler_service.py", line 25, in create_job
    'time_zone': 'utc'
  File "C:\Users\louis\AppData\Local\Programs\Python\Python36\lib\site-packages\google\cloud\scheduler_v1\services\cloud_scheduler\client.py", line 487, in create_job
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "C:\Users\louis\AppData\Local\Programs\Python\Python36\lib\site-packages\google\api_core\gapic_v1\method.py", line 145, in call
    return wrapped_func(*args, **kwargs)
  File "C:\Users\louis\AppData\Local\Programs\Python\Python36\lib\site-packages\google\api_core\grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 Invalid resource field value in the request.
```

**Comment by BinarSkugga** [comment]
I believe I have found a possible fix. While the location_path method isn't present anymore, providing the parent (specified as optional) fixes the issue. Might want to update the docs.

**Comment by BinarSkugga** [comment]
Closing because there is a workaround and no one seems active on the repository.
